/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setSecret"];
        post?: never;
        delete: operations["removeSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePreset"];
        post?: never;
        delete: operations["deletePreset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rescan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPresets"];
        put?: never;
        post: operations["createPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAnalyses"];
        put?: never;
        post: operations["startAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rerunAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSecrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetSecretRequest: {
            value: string;
        };
        SecretStatusDto: {
            name?: string;
            source?: string;
            maskedValue?: string;
        };
        SavePresetRequest: {
            name: string;
            values: {
                [key: string]: unknown;
            };
        };
        PresetDto: {
            id?: string;
            name?: string;
            values?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            updatedAt?: string;
        };
        ImportResultDto: {
            /** Format: int32 */
            scanned?: number;
            /** Format: int32 */
            created?: number;
            /** Format: int32 */
            updated?: number;
            /** Format: int32 */
            unchanged?: number;
        };
        StartAnalysisRequest: {
            ticker: string;
            /** Format: date */
            tradeDate: string;
            /** @enum {string} */
            assetType?: "STOCK" | "CRYPTO";
            analysts: ("MARKET" | "SOCIAL" | "NEWS" | "FUNDAMENTALS")[];
            llmProvider: string;
            deepThinkLlm: string;
            quickThinkLlm: string;
            /** Format: int32 */
            maxDebateRounds?: number;
            /** Format: int32 */
            maxRiskDiscussRounds?: number;
            outputLanguage?: string;
            checkpointEnabled?: boolean;
        };
        AnalysisDto: {
            id?: string;
            spec?: components["schemas"]["AnalysisSpecDto"];
            /** @enum {string} */
            status?: "QUEUED" | "RUNNING" | "COMPLETED" | "STOPPED" | "FAILED";
            /** @enum {string} */
            source?: "PLATFORM" | "EXTERNAL";
            /** @enum {string} */
            rating?: "BUY" | "OVERWEIGHT" | "HOLD" | "UNDERWEIGHT" | "SELL" | "REVIEW";
            decision?: string;
            stats?: components["schemas"]["RunStatsDto"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            errorCode?: string;
            errorMessage?: string;
        };
        AnalysisSpecDto: {
            ticker?: string;
            /** Format: date */
            tradeDate?: string;
            /** @enum {string} */
            assetType?: "STOCK" | "CRYPTO";
            analysts?: ("MARKET" | "SOCIAL" | "NEWS" | "FUNDAMENTALS")[];
            llmProvider?: string;
            deepThinkLlm?: string;
            quickThinkLlm?: string;
            /** Format: int32 */
            maxDebateRounds?: number;
            /** Format: int32 */
            maxRiskDiscussRounds?: number;
            outputLanguage?: string;
            checkpointEnabled?: boolean;
        };
        RunStatsDto: {
            /** Format: int64 */
            llmCalls?: number;
            /** Format: int64 */
            toolCalls?: number;
            /** Format: int64 */
            tokensIn?: number;
            /** Format: int64 */
            tokensOut?: number;
            costUsd?: number;
            /** Format: int64 */
            elapsedMs?: number;
        };
        AnalystOptionDto: {
            id?: string;
            agent?: string;
        };
        CatalogDto: {
            upstreamVersion?: string;
            defaults?: components["schemas"]["ModelDefaultsDto"];
            providers?: components["schemas"]["ProviderDto"][];
            analysts?: components["schemas"]["AnalystOptionDto"][];
            assetTypes?: string[];
        };
        ModelDefaultsDto: {
            llmProvider?: string;
            deepThinkLlm?: string;
            quickThinkLlm?: string;
        };
        ModelOptionDto: {
            id?: string;
            label?: string;
        };
        ProviderDto: {
            id?: string;
            apiKeyEnv?: string;
            customModelAllowed?: boolean;
            quickModels?: components["schemas"]["ModelOptionDto"][];
            deepModels?: components["schemas"]["ModelOptionDto"][];
        };
        AnalysisReportDto: {
            sections?: {
                [key: string]: string;
            };
            debates?: {
                [key: string]: string;
            };
            /** @enum {string} */
            rating?: "BUY" | "OVERWEIGHT" | "HOLD" | "UNDERWEIGHT" | "SELL" | "REVIEW";
            sources?: string[];
            /** Format: date-time */
            modifiedAt?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSecretRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretStatusDto"];
                };
            };
        };
    };
    removeSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePresetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetDto"];
                };
            };
        };
    };
    deletePreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rescan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultDto"];
                };
            };
        };
    };
    listPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetDto"][];
                };
            };
        };
    };
    createPreset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePresetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetDto"];
                };
            };
        };
    };
    listAnalyses: {
        parameters: {
            query?: {
                status?: "QUEUED" | "RUNNING" | "COMPLETED" | "STOPPED" | "FAILED";
                ticker?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"][];
                };
            };
        };
    };
    startAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAnalysisRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"];
                };
            };
        };
    };
    stopAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"];
                };
            };
        };
    };
    rerunAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"];
                };
            };
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretStatusDto"][];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDto"];
                };
            };
        };
    };
    getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"];
                };
            };
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReportDto"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
}
